=== beyond-aion/aion-server/game-server/data/static_data/spawns/spawns.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../global_types.xsd" />
	<xs:include schemaLocation="../import.xsd" />
	<xs:element name="spawns" type="SpawnsData" />

	<xs:complexType name="SpawnsData">
		<xs:sequence>
			<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="spawn_map" type="SpawnMap" minOccurs="0" maxOccurs="unbounded">
				<xs:unique name="unique-npc-id"><!-- a spawn entry must be unique per npc_id (see SpawnData#afterUnmarshal) -->
					<!-- entry with same npc_id may appear twice if one has custom="true" -->
					<xs:selector xpath="spawn" />
					<xs:field xpath="@npc_id" />
					<xs:field xpath="@custom" />
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SpawnMap">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="base_spawn" type="BaseSpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="rift_spawn" type="RiftSpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="siege_spawn" type="SiegeSpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="vortex_spawn" type="VortexSpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="mercenary_spawn" type="MercenarySpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ahserion_spawn" type="AhserionsFlightSpawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="map_id" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="BaseSpawn">
		<xs:sequence>
			<xs:element name="simple_race" type="SimpleRaceTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int"/>
		<xs:attribute name="world" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="SimpleRaceTemplate">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="race" type="Race" use="required" />
	</xs:complexType>
	<xs:complexType name="RiftSpawn">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int"/>
		<xs:attribute name="world" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="VortexSpawn">
		<xs:sequence>
			<xs:element name="state_type" type="VortexStateTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="VortexStateTemplate">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="state" type="StateType"/>
	</xs:complexType>
	<xs:complexType name="AhserionsFlightSpawn">
		<xs:sequence>
			<xs:element name="ahserion_stage_spawn" type="AhserionStageSpawnTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="faction" type="PanesterraFaction"/>
	</xs:complexType>
	<xs:complexType name="AhserionStageSpawnTemplate">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="stage" type="xs:int"/>
	</xs:complexType>
	<xs:simpleType name="PanesterraFaction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BELUS"/>
			<xs:enumeration value="ASPIDA"/>
			<xs:enumeration value="ATANATOS"/>
			<xs:enumeration value="DISILLON"/>
			<xs:enumeration value="BALAUR"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="StateType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="INVASION"/>
			<xs:enumeration value="PEACE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="SiegeSpawn">
		<xs:sequence>
			<xs:element name="siege_race" type="SiegeRaceTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="siege_id" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="SiegeRaceTemplate">
		<xs:sequence>
			<xs:element name="siege_mod" type="SiegeModTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="race" type="SiegeRaceType"/>
	</xs:complexType>
	<xs:complexType name="SiegeModTemplate">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="mod" type="SiegeModType"/>
	</xs:complexType>
	<xs:complexType name="MercenarySpawn">		
		<xs:sequence>
			<xs:element name="mercenary_race" type="MercenaryRace" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="siege_id" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="MercenaryRace">		
		<xs:sequence>
			<xs:element name="mercenary_zone" type="MercenaryZone" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="race" type="Race"/>
	</xs:complexType>
	<xs:complexType name="MercenaryZone">		
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="zone" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="Spawn">
		<xs:sequence>
			<xs:element name="temporary_spawn" type="TemporarySpawn" minOccurs="0" maxOccurs="1"/>
			<xs:element name="spot" type="SpawnSpotTemplate" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="npc_id" type="xs:int" use="required"/>
		<xs:attribute name="pool" type="xs:int" use="optional"/>
		<xs:attribute name="respawn_time" type="xs:int"/>
		<xs:attribute name="handler" type="SpawnHandlerType"/>
		<xs:attribute name="custom" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="difficult_id" type="xs:byte"/>
	</xs:complexType>
	<xs:complexType name="SpawnSpotTemplate">
		<xs:sequence>
			<xs:element name="temporary_spawn" type="TemporarySpawn" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="x" type="xs:float"/>
		<xs:attribute name="y" type="xs:float"/>
		<xs:attribute name="z" type="xs:float"/>
		<xs:attribute name="h" type="HeadingType" use="optional" default="0"/>
		<xs:attribute name="static_id" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="random_walk" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="walker_id" type="xs:string"/>
		<xs:attribute name="walker_index" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="fly" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="anchor" type="xs:string"/>
		<xs:attribute name="state" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="ai" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="TemporarySpawn">
		<xs:attribute name="weekdays" type="WeekdayList"/>
		<xs:attribute name="spawn_time" type="xs:string"/>
		<xs:attribute name="despawn_time" type="xs:string"/>
	</xs:complexType>
	<xs:simpleType name="WeekdayList">
		<xs:list itemType="Weekday" />
	</xs:simpleType>
	<xs:simpleType name="Weekday">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MONDAY"/>
			<xs:enumeration value="TUESDAY"/>
			<xs:enumeration value="WEDNESDAY"/>
			<xs:enumeration value="THURSDAY"/>
			<xs:enumeration value="FRIDAY"/>
			<xs:enumeration value="SATURDAY"/>
			<xs:enumeration value="SUNDAY"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SiegeModType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PEACE"/>
			<xs:enumeration value="SIEGE"/>
			<xs:enumeration value="LANDING"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="HeadingType">
		<xs:restriction base="xs:byte">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="120"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SiegeRaceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ELYOS"/>
			<xs:enumeration value="ASMODIANS"/>
			<xs:enumeration value="BALAUR"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SpawnHandlerType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ATTACKER"/>
			<xs:enumeration value="BOSS"/>
			<xs:enumeration value="FLAG"/>
			<xs:enumeration value="GUARDIAN"/>
			<xs:enumeration value="MERCHANT"/>			
			<xs:enumeration value="OUTRIDER"/>
			<xs:enumeration value="OUTRIDER_ENHANCED"/>
			<xs:enumeration value="RIFT"/>
			<xs:enumeration value="SENTINEL"/>
			<xs:enumeration value="STATIC"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== beyond-aion/aion-server/game-server/data/static_data/spawns/Npcs/Custom/Skill_CD_Reset_Shugo.xml
<?xml version="1.0" encoding="utf-8"?>
<spawns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../spawns.xsd">
	<!-- Sanctum Arena -->
	<spawn_map map_id="110010000">
		<spawn npc_id="833543" respawn_time="295">
			<spot x="1422.7744" y="1250.0612" z="569.47" h="16" ai="customcdreset" />
		</spawn>
	</spawn_map>
	<!-- Pandaemonium Arena -->
	<spawn_map map_id="120010000">
		<spawn npc_id="833543" respawn_time="295">
			<spot x="930.0757" y="1604.4641" z="225.6" h="105" ai="customcdreset" />
		</spawn>
	</spawn_map>
	<!-- Discipline Training Grounds -->
	<spawn_map map_id="300430000">
		<spawn npc_id="833543" respawn_time="295">
			<!-- The Plaza of Struggle -->
			<spot x="1831.303" y="1719.6138" z="305.14697" h="15" ai="customcdreset" />
			<!-- Red Sand Arena -->
			<spot x="1856.4928" y="1075.8822" z="338.22055" h="87" ai="customcdreset" />
			<!-- Abyss Bridge -->
			<spot x="294.2966" y="1245.7626" z="268.07672" h="54" ai="customcdreset" />
			<!-- Collapsed Wind Tower -->
			<spot x="685.91534" y="1776.664" z="188.9151" h="51" ai="customcdreset" />
		</spawn>
	</spawn_map>
</spawns>

=== beyond-aion/aion-server/game-server/data/static_data/spawns/Instances/300220000_Abyssal_Splinter.xml
<?xml version="1.0" encoding="utf-8"?>
<spawns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../spawns.xsd">
	<spawn_map map_id="300220000">
		<!-- Abyssal Splinter Exit -->
		<spawn npc_id="730317">
			<spot x="719.756" y="161.833" z="449.343" h="40" />
		</spawn>
		<!-- Ancient Treasure Box -->
		<spawn npc_id="700859">
			<spot x="270.4710" y="743.9896" z="319.3749" h="106" />
			<spot x="280.9925" y="767.5568" z="287.4333" h="66" />
			<spot x="290.2162" y="729.6007" z="253.7787" h="16" />
			<spot x="306.5070" y="715.2716" z="368.3994" h="6" />
			<spot x="311.6450" y="768.0681" z="343.8409" h="106" />
			<spot x="344.2876" y="778.7310" z="397.5779" h="33" />
			<spot x="346.9677" y="742.3782" z="365.1365" />
			<spot x="347.3535" y="735.8599" z="419.6725" h="66" />
			<spot x="350.4549" y="788.7392" z="320.6760" h="106" />
			<spot x="360.1270" y="684.1302" z="390.9752" h="33" />
			<spot x="368.2921" y="771.3032" z="347.4754" />
			<spot x="389.8283" y="763.1230" z="274.2615" h="40" />
		</spawn>
		<!-- Ametgolem of Guarding -->
		<spawn npc_id="281892">
			<spot x="641.285" y="235.285" z="461.537" h="99" />
			<spot x="641.285" y="269.285" z="462.537" h="99" />
			<spot x="641.285" y="305.285" z="465.548" h="95" />
			<spot x="647.185" y="236.857" z="461.724" h="95" />
			<spot x="647.185" y="270.857" z="462.724" h="95" />
			<spot x="651.049" y="305.857" z="465.449" h="91" />
		</spawn>
		<!-- Artifact of Protection -->
		<spawn npc_id="700856">
			<spot x="326.1492" y="766.9335" z="203.1832" static_id="60" />
		</spawn>
		<!-- Broken Orkanimum -->
		<spawn npc_id="700862">
			<spot x="814.7477" y="645.96875" z="455.1076" h="72" />
		</spawn>
		<!-- Cobweb -->
		<spawn npc_id="281910">
			<spot x="609.261" y="531.14" z="422.934" h="31" />
			<spot x="612.141" y="533.823" z="423.074" h="60" />
			<spot x="636.373" y="521.948" z="422.582" h="101" />
			<spot x="637.072" y="520.309" z="422.508" h="5" />
			<spot x="637.779" y="522.234" z="422.612" h="89" />
			<spot x="649.303" y="522.958" z="422.83" h="75" />
			<spot x="650.114" y="519.787" z="422.678" h="19" />
			<spot x="652.279" y="523.013" z="422.895" h="86" />
			<spot x="664.625" y="560.155" z="424.873" h="117" />
			<spot x="666.675" y="546.268" z="423.794" h="5" />
			<spot x="666.815" y="549.765" z="423.896" h="14" />
			<spot x="669.7" y="550.116" z="424.053" h="40" />
		</spawn>
		<!-- Dayshade -->
		<spawn npc_id="282010">
			<spot x="451.28616" y="692.8484" z="433.7726" h="113" />
		</spawn>
		<!-- Enos Grappler -->
		<spawn npc_id="216944" respawn_time="295">
			<spot x="534.35" y="666.26" z="426.174" h="118" walker_id="A13125A1C9E947E8E257E47D0E4B283792C51DCF" />
		</spawn>
		<!-- Enos Watcher -->
		<spawn npc_id="216945">
			<spot x="520.753" y="666.508" z="428.082" />
			<spot x="577.435" y="636.91" z="419.118" h="75" />
			<spot x="642.639" y="152.14" z="449.398" h="11" />
		</spawn>
		<!-- Fallen Shugo -->
		<spawn npc_id="207945">
			<spot x="671.21484" y="420.37387" z="462.78702" h="56" />
		</spawn>
		<!-- Flash Lapilimo -->
		<spawn npc_id="216947" respawn_time="295">
			<spot x="756.64" y="648.51" z="445.75342" h="2" walker_id="4F937FA787F5BC71F67B8A8152BC13AE7D63E15D" />
			<spot x="796.89" y="617.22" z="455.28043" h="67" walker_id="2285FAA1A584706883E4869C3DD5D021D106F674" />
			<spot x="808.18" y="647.51" z="454.8155" h="106" walker_id="195B74A903ECAFCC55F50AFB58F17B1DBC0A07DA" />
		</spawn>
		<!-- Flash Lapilimo -->
		<spawn npc_id="216958" respawn_time="295">
			<spot x="780.35" y="651.83" z="449.6864" h="26" walker_id="24B3765F75E127A680AB761E52988FE8464FE723" />
		</spawn>
		<!-- Flash Lapilimo -->
		<spawn npc_id="216959" respawn_time="295">
			<spot x="707.61" y="619.79" z="430.36194" h="23" walker_id="2F03BD9F46C82E447442476F3C6DDFC08252B816" />
			<spot x="756.76" y="600.93" z="462.77676" h="89" walker_id="F7EFF7C6F9DBB93A5523E7029389FAE4A602D80D" />
		</spawn>
		<!-- Holy Orkanimum -->
		<spawn npc_id="216953">
			<spot x="301.997" y="737.567" z="197.37" h="105" />
			<spot x="318.391" y="740.69" z="204.592" h="88" />
			<spot x="321.052" y="734.077" z="216.213" h="82" />
			<spot x="329.62" y="734.051" z="197.612" h="85" />
			<spot x="329.718" y="733.969" z="197.611" h="78" />
			<spot x="335.238" y="708.266" z="197.696" h="53" />
			<spot x="338.225" y="721.117" z="207.172" h="65" />
			<spot x="341.568" y="731.227" z="200.19" h="79" />
			<spot x="361.69" y="742.071" z="197.301" h="75" />
		</spawn>
		<!-- Kaluva the Fourth Fragment -->
		<spawn npc_id="216950">
			<spot x="634.77765" y="557.0182" z="425.0" h="113" />
		</spawn>
		<!-- Noble Lapilima -->
		<spawn npc_id="216946" respawn_time="295">
			<spot x="737.5" y="645.28" z="439.23276" h="72" walker_id="C3C4E358C346EA0C647E71384C67F9B905240DEC" />
			<spot x="790.75" y="656.64" z="452.78162" h="68" walker_id="3AE40F96FE1301994C6BB291D8B658F3440C50B2" />
		</spawn>
		<!-- Noble Lapilima -->
		<spawn npc_id="216957" respawn_time="295">
			<spot x="762.52" y="605.41" z="461.67227" h="16" walker_id="B24B50292211760AC12BFB8A569350D07AD0C147" />
			<spot x="807.04" y="630.01" z="454.5897" h="90" walker_id="692608956D57FF2AB5AC6B0CBC0A3D29E3F04A83" />
		</spawn>
		<!-- Pazuzu -->
		<spawn npc_id="216951">
			<spot x="669.5757" y="335.1355" z="467.42245" h="76" />
		</spawn>
		<!-- Polearm of Akarios -->
		<spawn npc_id="700864">
			<spot x="398.192" y="682.253" z="439.470" h="76" />
		</spawn>
		<!-- Summoned Orkanimum -->
		<spawn npc_id="281903">
			<spot x="644.708" y="267.345" z="462.163" h="90" />
			<spot x="644.713" y="233.206" z="461.178" h="95" />
			<spot x="646.652" y="304.345" z="465.583" h="89" />
		</spawn>
		<!-- Teleportation Device -->
		<spawn npc_id="281905">
			<spot x="302.201" y="735.16" z="197.668" h="17" />
			<spot x="334.001" y="707.736" z="197.779" h="32" />
			<spot x="362.192" y="741.592" z="197.301" h="67" />
		</spawn>
		<!-- Worn Book -->
		<spawn npc_id="700865">
			<spot x="447.703" y="728.164" z="437.768" h="72" />
		</spawn>
	</spawn_map>
</spawns>

=== beyond-aion/aion-server/game-server/data/static_data/spawns/Gather/300600000_Unstable_Abyssal_Splinter.xml
<?xml version="1.0" encoding="UTF-8"?>
<spawns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../spawns.xsd">
	<spawn_map map_id="300600000">
    <!-- Drenite -->
		<spawn npc_id="400213">
			<spot x="302.412" y="683.901" z="197.270"/>
			<spot x="344.106" y="644.372" z="213.051"/>
			<spot x="287.674" y="714.413" z="197.572"/>
			<spot x="294.879" y="750.483" z="197.370"/>
			<spot x="350.896" y="761.749" z="197.103"/>
			<spot x="378.344" y="676.846" z="232.612"/>
			<spot x="389.593" y="700.073" z="233.877"/>
			<spot x="358.889" y="688.967" z="234.342"/>
			<spot x="387.855" y="662.092" z="227.038"/>
			<spot x="370.367" y="760.203" z="197.263"/>
			<spot x="357.815" y="699.802" z="197.225"/>
		</spawn>
		<!-- Turquoise -->
		<spawn npc_id="400324">
			<spot x="398.945" y="686.064" z="232.955"/>
			<spot x="301.899" y="661.059" z="199.934"/>
			<spot x="378.255" y="640.998" z="221.347"/>
			<spot x="292.238" y="690.632" z="197.211"/>
			<spot x="287.241" y="670.074" z="196.948"/>
			<spot x="400.571" y="678.996" z="229.873"/>
			<spot x="365.387" y="658.962" z="217.666"/>
			<spot x="385.819" y="640.482" z="223.433"/>
			<spot x="398.406" y="690.125" z="231.804"/>
			<spot x="316.804" y="691.096" z="197.654"/>
			<spot x="285.062" y="678.778" z="196.940"/>
			<spot x="291.197" y="688.398" z="197.234"/>
		</spawn>
	</spawn_map>
</spawns>
