=== beyond-aion/aion-server/game-server/data/static_data/siege/siege_locations.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">
	<xs:include schemaLocation="../zones/zones.xsd"/>
	<xs:include schemaLocation="../global_types.xsd" />
	<xs:include schemaLocation="../world_maps.xsd"/>
	<xs:include schemaLocation="../import.xsd"/>
	<xs:element name="siege_locations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="siege_location" type="siegelocation" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="siegelocation">
		<xs:sequence>
			<xs:element name="artifact_activation" type="ArtifactActivation" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="siege_reward" type="SiegeReward" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="legion_reward" type="SiegeLegionReward" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="merc_zone" type="SiegeMercenaryZone" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="assault_data" type="AssaultData" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required"/>
		<xs:attribute name="type" type="SiegeType" use="required"/>
		<xs:attribute name="world" type="xs:int" use="required"/>
		<xs:attribute name="name_id" type="xs:int"/>
		<xs:attribute name="fortress_dependency" type="IntListType"/>
		<xs:attribute name="siege_duration" type="xs:int" use="optional" default="-1"/>
		<xs:attribute name="influence" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="legion_gp" type="xs:int"/>
		<xs:attribute name="occupy_count" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="kinah_rewards" type="IntListType" use="optional" default="0"/>
	</xs:complexType>

	<xs:simpleType name="SiegeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FORTRESS"/>
			<xs:enumeration value="ARTIFACT"/>
			<xs:enumeration value="OUTPOST"/>
			<xs:enumeration value="AGENT_FIGHT"/>
			<xs:enumeration value="INDUN"/>
			<xs:enumeration value="UNDERPASS"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AssaulterType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TELEPORT"/>
			<xs:enumeration value="COMMANDER"/>
			<xs:enumeration value="FIGHTER"/>
			<xs:enumeration value="RANGER"/>
			<xs:enumeration value="ASSASSIN"/>
			<xs:enumeration value="GUNNER"/>
			<xs:enumeration value="PRIEST"/>
			<xs:enumeration value="WITCH"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ArtifactActivation">
		<xs:attribute name="item_id" type="xs:int" use="optional" default="188020000"/>
		<xs:attribute name="count" type="xs:int" use="optional" default="1"/>
		<xs:attribute name="skill" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="repeat_count" type="xs:int" use="optional" default="1"/>
		<xs:attribute name="repeat_interval" type="xs:int" use="optional" default="1"/>
		<xs:attribute name="cd" type="xs:int" use="optional" default="3600"/>
	</xs:complexType>
	<xs:complexType name="SiegeReward">
		<xs:attribute name="top" type="xs:int" use="required"/>
		<xs:attribute name="item_id" type="xs:int" use="required"/>
		<xs:attribute name="item_count" type="xs:int" use="required"/>
		<xs:attribute name="gp_win" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="gp_defeat" type="xs:int" use="optional" default="0"/>
	</xs:complexType>
	<xs:complexType name="SiegeLegionReward">
		<xs:attribute name="item_id" type="xs:int" use="required"/>
		<xs:attribute name="item_count" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="SiegeMercenaryZone">
		<xs:attribute name="id" type="xs:int" use="required"/>
		<xs:attribute name="costs" type="xs:int" use="required"/>
		<xs:attribute name="cooldown" type="xs:int" use="required"/>
		<xs:attribute name="msg_id" type="xs:int" use="required"/>
		<xs:attribute name="announce_id" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="AssaultData">
		<xs:sequence>
			<xs:element name="assaulter" type="AssaulterTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="dredgion_id" type="xs:int"/>
		<xs:attribute name="base_budget" type="xs:int"/>
		<xs:attribute name="base_delay" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="AssaulterTemplate">
		<xs:attribute name="type" type="AssaulterType"/>
		<xs:attribute name="npc_ids" type="IntListType"/>
		<xs:attribute name="heading_offset" type="xs:int"/>
		<xs:attribute name="distance_offset" type="xs:int"/>
	</xs:complexType>
</xs:schema>

=== beyond-aion/aion-server/game-server/data/static_data/siege/siege_locations.xml
<?xml version="1.0" encoding="UTF-8"?>
<siege_locations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="siege_locations.xsd">
	<siege_location id="0" type="UNDERPASS" world="210050000"/>
	<siege_location id="0" type="UNDERPASS" world="220070000"/>
	<siege_location id="0" type="UNDERPASS" world="600100000"/>
	<siege_location id="3" type="INDUN" world="210020000"/>
	<siege_location id="3" type="INDUN" world="220020000"/>
	<siege_location id="4" type="INDUN" world="210040000"/>
	<siege_location id="5" type="INDUN" world="220040000"/>
	<siege_location id="6" type="INDUN" world="220050000"/>
	<siege_location id="6" type="INDUN" world="210060000"/>
	<siege_location id="8" type="INDUN" world="220020000"/>
	<siege_location id="7" type="INDUN" world="220050000"/>
	<siege_location id="8" type="INDUN" world="220020000"/>
	<siege_location id="8" type="INDUN" world="210020000"/>
	<siege_location id="8" type="INDUN" world="400010000"/>
	<siege_location id="9" type="INDUN" world="220040000"/>
	<siege_location id="9" type="INDUN" world="210040000"/>
	<siege_location id="9" type="INDUN" world="400010000"/>
	<siege_location id="18" type="INDUN" world="120010000"/>
	<siege_location id="18" type="INDUN" world="110010000"/>
	<siege_location id="25" type="INDUN" world="210040000"/>
	<siege_location id="26" type="INDUN" world="210050000"/>
	<siege_location id="26" type="INDUN" world="220070000"/>
	<siege_location id="27" type="INDUN" world="210050000"/>
	<siege_location id="27" type="INDUN" world="220070000"/>
	<siege_location id="28" type="INDUN" world="600010000"/>
	<siege_location id="29" type="INDUN" world="210050000"/>
	<siege_location id="29" type="INDUN" world="220070000"/>
	<siege_location id="45" type="INDUN" world="220040000"/>
	<siege_location id="45" type="INDUN" world="210040000"/>
	<siege_location id="46" type="INDUN" world="210030000"/>
	<siege_location id="46" type="INDUN" world="220030000"/>
	<siege_location id="49" type="INDUN" world="210070000"/>
	<siege_location id="49" type="INDUN" world="220080000"/>
	<siege_location id="50" type="INDUN" world="220080000"/>
	<siege_location id="50" type="INDUN" world="210070000"/>
	<siege_location id="54" type="INDUN" world="110070000"/>
	<siege_location id="54" type="INDUN" world="120080000"/>
	<siege_location id="57" type="INDUN" world="110070000"/>
	<siege_location id="57" type="INDUN" world="120080000"/>
	<siege_location id="61" type="INDUN" world="110070000"/>
	<siege_location id="61" type="INDUN" world="120080000"/>
	<siege_location id="62" type="INDUN" world="120080000"/>
	<siege_location id="62" type="INDUN" world="110070000"/>
	<siege_location id="68" type="INDUN" world="220070000"/>
	<siege_location id="68" type="INDUN" world="210050000"/>
	<siege_location id="69" type="INDUN" world="110070000"/>
	<siege_location id="69" type="INDUN" world="120080000"/>
	<siege_location id="70" type="INDUN" world="120080000"/>
	<siege_location id="70" type="INDUN" world="110070000"/>
	<siege_location id="74" type="INDUN" world="120080000"/>
	<siege_location id="74" type="INDUN" world="110070000"/>
	<siege_location id="75" type="INDUN" world="120010000"/>
	<siege_location id="75" type="INDUN" world="110010000"/>
	<siege_location id="77" type="INDUN" world="220080000"/>
	<siege_location id="77" type="INDUN" world="210070000"/>
	<siege_location id="80" type="INDUN" world="210070000"/>
	<siege_location id="80" type="INDUN" world="220080000"/>
	<siege_location id="81" type="INDUN" world="210070000"/>
	<siege_location id="81" type="INDUN" world="220080000"/>
	<siege_location id="83" type="INDUN" world="600090000"/>
	<siege_location id="84" type="INDUN" world="120080000"/>
	<siege_location id="84" type="INDUN" world="110070000"/>
	<siege_location id="86" type="INDUN" world="120080000"/>
	<siege_location id="86" type="INDUN" world="110070000"/>
	<siege_location id="88" type="INDUN" world="210070000"/>
	<siege_location id="88" type="INDUN" world="220080000"/>
	<siege_location id="91" type="INDUN" world="600010000"/>
	<siege_location id="94" type="INDUN" world="600100000"/>
	<siege_location id="97" type="INDUN" world="120080000"/>
	<siege_location id="97" type="INDUN" world="110070000"/>
	<siege_location id="99" type="INDUN" world="600090000"/>
	<siege_location id="103" type="INDUN" world="600100000"/>
	<siege_location id="104" type="INDUN" world="220080000"/>
	<siege_location id="104" type="INDUN" world="210070000"/>
	<siege_location id="116" type="INDUN" world="600100000"/>
	<siege_location id="121" type="INDUN" world="600100000"/>
	<siege_location id="131" type="INDUN" world="600090000"/>
	<siege_location id="132" type="INDUN" world="600100000"/>
	<siege_location id="134" type="INDUN" world="220080000"/>
	<siege_location id="134" type="INDUN" world="210070000"/>
	<siege_location id="135" type="INDUN" world="220080000"/>
	<siege_location id="135" type="INDUN" world="210070000"/>
	<siege_location id="137" type="INDUN" world="210070000"/>
	<siege_location id="137" type="INDUN" world="220080000"/>
	<siege_location id="138" type="INDUN" world="220080000"/>
	<siege_location id="138" type="INDUN" world="210070000"/>
	<siege_location id="140" type="INDUN" world="220080000"/>
	<siege_location id="140" type="INDUN" world="210070000"/>
	<siege_location id="1011" type="FORTRESS" world="400010000" name_id="400910" occupy_count="2" legion_gp="1000" siege_duration="3000" influence="10">
		<artifact_activation itemid="188020000" count="1" skill="12078" cd="7200"/>
		<siege_reward top="11" itemid="186000242" m_count="4" gp_win="300" gp_defeat="150"/>
		<siege_reward top="22" itemid="186000242" m_count="3" gp_win="250" gp_defeat="125"/>
		<siege_reward top="50" itemid="186000242" m_count="2" gp_win="200" gp_defeat="100"/>
		<siege_reward top="200" itemid="186000242" m_count="1" gp_win="100" gp_defeat="50"/>
		<legion_reward itemid="182400001" m_count="30000000" />
		<legion_reward itemid="186000242" m_count="1"/>
		<legion_reward itemid="188052117" m_count="1"/>
		<legion_reward itemid="122001663" m_count="1"/>
		<merc_zone id="1" costs="36" cooldown="900" msg_id="1402451" announce_id="1402448"/>
		<merc_zone id="2" costs="36" cooldown="900" msg_id="1402452" announce_id="1402449"/>
	</siege_location>
	<siege_location id="1012" type="ARTIFACT" world="400010000">
		<artifact_activation itemid="188020002" count="2" skill="12181" repeat_count="5" repeat_interval="4" cd="900"/>
	</siege_location>
	<siege_location id="1013" type="ARTIFACT" world="400010000">
		<artifact_activation itemid="188020000" count="3" skill="12180" repeat_count="5" repeat_interval="4" cd="900"/>
	</siege_location>
	<siege_location id="1014" type="ARTIFACT" world="400010000">
		<artifact_activation itemid="188020000" count="3" skill="12180" repeat_count="5" repeat_interval="4" cd="900"/>
	</siege_location>
	<siege_location id="1015" type="ARTIFACT" world="400010000">
		<artifact_activation itemid="188020000" count="3" skill="12180" repeat_count="5" repeat_interval="4" cd="900"/>
	</siege_location>
	<siege_location id="1016" type="ARTIFACT" world="400010000">
		<artifact_activation itemid="188020000" count="3" skill="12180" repeat_count="5" repeat_interval="4" cd="900"/>
	</siege_location>
	<siege_location id="1017" type="ARTIFACT" world="400010000">
		<artifact_activation itemid="188020002" count="2" skill="12181" repeat_count="5" repeat_interval="4" cd="900"/>
	</siege_location>
	<siege_location id="1018" type="ARTIFACT" world="400010000">
		<artifact_activation itemid="188020002" count="2" skill="12181" repeat_count="5" repeat_interval="4" cd="900"/>
	</siege_location>
	<siege_location id="1019" type="ARTIFACT" world="400010000">
		<artifact_activation itemid="188020002" count="2" skill="12181" repeat_count="5" repeat_interval="4" cd="900"/>
	</siege_location>
	<siege_location id="1020" type="ARTIFACT" world="400010000">
		<artifact_activation itemid="188020000" count="3" skill="12180" repeat_count="5" repeat_interval="4" cd="900"/>
	</siege_location>
	<siege_location id="1131" type="FORTRESS" world="400010000" name_id="400911" occupy_count="2" siege_duration="3600" influence="3">
		<artifact_activation itemid="188020000" count="1" skill="12147" repeat_count="1" repeat_interval="1" cd="3600"/>
		<siege_reward top="12" itemid="186000096" m_count="3"/>
		<siege_reward top="20" itemid="186000030" m_count="3"/>
		<siege_reward top="30" itemid="186000030" m_count="2"/>
		<siege_reward top="40" itemid="186000031" m_count="3"/>
		<legion_reward itemid="182400001" m_count="5000000" />
		<legion_reward itemid="186000096" m_count="3"/>
		<legion_reward itemid="186000030" m_count="20"/>
		<legion_reward itemid="186000031" m_count="60"/>
		<legion_reward itemid="188051893" m_count="1"/>
		<legion_reward itemid="122001519" m_count="1"/>
	</siege_location>
	<siege_location id="1132" type="FORTRESS" world="400010000" name_id="400912" occupy_count="2" siege_duration="3600" influence="3">
		<artifact_activation itemid="188020000" count="1" skill="12148" repeat_count="1" repeat_interval="1" cd="3600"/>
		<siege_reward top="12" itemid="186000096" m_count="3"/>
		<siege_reward top="20" itemid="186000030" m_count="3"/>
		<siege_reward top="30" itemid="186000030" m_count="2"/>
		<siege_reward top="40" itemid="186000031" m_count="3"/>
		<legion_reward itemid="182400001" m_count="5000000" />
		<legion_reward itemid="186000096" m_count="3"/>
		<legion_reward itemid="186000030" m_count="20"/>
		<legion_reward itemid="186000031" m_count="60"/>
		<legion_reward itemid="188051893" m_count="1"/>
		<legion_reward itemid="122001520" m_count="1"/>
	</siege_location>
	<siege_location id="1133" type="ARTIFACT" world="400010000">
		<artifact_activation itemid="188020000" count="2" skill="12043" repeat_count="1" repeat_interval="1" cd="2700"/>
	</siege_location>
	<siege_location id="1134" type="ARTIFACT" world="400010000">
		<artifact_activation itemid="188020000" count="2" skill="12043" repeat_count="1" repeat_interval="1" cd="2700"/>
